name: Big Borther Watches
on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: --bin big_brother
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.5.0
        with:
          default_author: github_actions
          add: '["*.json"]'
